version: "3.9"
services:
  frigate:
    container_name: frigate
#    privileged: true # this may not be necessary for all setups
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$tzone
      - FRIGATE_RTSP_PASSWORD="$pass"
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    #devices:
    #  - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    #  - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #  - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${app_data}/frigate:/config
      - ${app_data}/frigate/config.yml:/config/config.yml:rw
      - ${app_data}/frigate/frigate.db:/media/frigate/frigate.db:rw
      - ${media}/nvr/recordings:/media/frigate/recordings
      - ${media}/nvr/clips:/media/frigate/clips
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "554:554" # RTSP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
networks:
    private:
        external: true
